# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8758923c19cf2b2028c9d7d15cebf9c7c18edb652b9d61670339bf75bfaffebdf342087e166a758b078df77f6ce45085292307dcd10d543e7fd9820cc0dee7d5

test:
  secret_key_base: 41991b1cbf059993e0a285788c14b7288d70ebbc1bd02b62074379eea7cb18ef6852d24240da16688635a1552a21d0a103ed218098366e011e05b7d98bc0dd39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
